## Python Programming Practice Exam

```
Scoring:
============
 0-11: fail (1),
12-14: pass (2),
15-17: satisfactory (3),
18-20: good (4),
21-24: excellent (5).
```

### Problem 1
<p style="text-align: right">(12 points)</p>

Write a program that asks two strings from the user and then prints the number of bigrams that appear in both strings.
By bigram we mean a substring of length 2, for instance the bigram decomposition of the string `papabear` is `pa`-`ap`-`pa`-`ab`-`be`-`ea`-`ar`. Example run:

```
1st string: papabear
2nd string: mamabear
Number of common bigrams: 4
```

In [9]:
in1 = input('Enter first string:  ')
in2 = input('Enter secon string:  ')
def bigram(inn):
    s = set()
    for i in range(len(inn)-1):
        s.add((inn[i]+inn[i+1]))
    return s

s1 = bigram(in1)
s2 = bigram(in2)
cnt = 0

#for c in s1:
#    if c in s2:
#        cnt += 1

cnt = len(s1&s2)

print (f'Number of common bigrams: {cnt}')

Enter first string:  papabear
Enter secon string:  mamabear
Number of common bigrams: 4

In [16]:
# solution 2
def bigrams(s):
    return set(zip(s[:-1], s[1:]))

s1 = input('1st string: ')
s2 = input('2nd string: ')
print('Number of common bigrams:', len(bigrams(s1) & bigrams(s2)))

1st string: papabear
2nd string: mamabear
Number of common bigrams: 4

### Problem 2
<p style="text-align: right">(12 points)</p>

The file [nba_games.txt](nba_games.txt) contains data about NBA basketball games, from season 2013 to season 2019. Write a program that loads the data and then answers the following questions:

**(a)**: What percentage of the games was won by the home team (the home team wins if `PTS_home` is greater than `PTS_away`)?<br>
**(b)**: How many games had more than 130 rebounds (based on the sum of `REB_home` and `REB_away`)?<br>
**(c)**: Which was the game with the largest point difference between the teams?<br>
**(d)**: What is the ranking of the teams, based on the number of games won?

In [23]:
import pandas as pd
import numpy as np
import itertools

In [13]:
data = pd.read_csv('nba_games.txt', sep='|', skiprows=1)
data

,SEASON,DATE,TEAM_home,TEAM_away,PTS_home,PTS_away,REB_home,REB_away,AST_home,AST_away,FG3_PCT_home,FG3_PCT_away
0,2019,2020-10-11,Miami Heat,Los Angeles Lakers,93,106,41,46,25,23,35.7,31.4
1,2019,2020-10-09,Los Angeles Lakers,Miami Heat,108,111,41,35,21,26,36.8,42.4
2,2019,2020-10-06,Miami Heat,Los Angeles Lakers,96,102,39,42,18,25,34.4,35.9
3,2019,2020-10-04,Miami Heat,Los Angeles Lakers,115,104,37,43,25,23,35.3,33.3
4,2019,2020-10-02,Los Angeles Lakers,Miami Heat,124,114,44,37,32,29,34.0,40.7
...,...,...,...,...,...,...,...,...,...,...,...,...
23367,2014,2014-10-06,Atlanta Hawks,New Orleans Pelicans,93,87,50,43,24,17,42.1,37.5
23368,2014,2014-10-06,Chicago Bulls,Washington Wizards,81,85,40,47,18,17,38.1,26.7
23369,2014,2014-10-06,Los Angeles Lakers,Denver Nuggets,98,95,45,43,29,19,50.0,50.0
23370,2014,2014-10-05,Toronto Raptors,Sacramento Kings,99,94,30,45,21,18,33.3,38.5
23371,2014,2014-10-04,Miami Heat,New Orleans Pelicans,86,98,42,42,18,19,33.3,43.8

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23372 entries, 0 to 23371
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SEASON        23372 non-null  int64
 1   DATE          23372 non-null  object
 2   TEAM_home     23372 non-null  object
 3   TEAM_away     23372 non-null  object
 4   PTS_home      23372 non-null  int64
 5   PTS_away      23372 non-null  int64
 6   REB_home      23372 non-null  int64
 7   REB_away      23372 non-null  int64
 8   AST_home      23372 non-null  int64
 9   AST_away      23372 non-null  int64
 10  FG3_PCT_home  23372 non-null  float64
 11  FG3_PCT_away  23372 non-null  float64
dtypes: float64(2), int64(7), object(3)
memory usage: 2.1+ MB

In [15]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
SEASON,23372.0,2010.973686,4.864080,2003.0,2007.0,2011.0,2015.0,2019.0
PTS_home,23372.0,102.268013,12.948549,36.0,93.0,102.0,111.0,168.0
PTS_away,23372.0,99.318030,13.015332,33.0,90.0,99.0,108.0,168.0
REB_home,23372.0,43.186548,6.606201,15.0,39.0,43.0,48.0,72.0
REB_away,23372.0,41.870786,6.498799,19.0,37.0,42.0,46.0,81.0
AST_home,23372.0,22.533459,5.152033,6.0,19.0,22.0,26.0,47.0
AST_away,23372.0,21.131824,5.082061,4.0,18.0,21.0,24.0,46.0
FG3_PCT_home,23372.0,35.552999,11.435611,0.0,28.3,35.5,42.9,100.0
FG3_PCT_away,23372.0,34.881871,11.240852,0.0,27.6,35.0,42.1,100.0

In [19]:
sum(data['PTS_home']>data['PTS_away'])/len(data)*100

59.37446517200069

In [21]:
sum((data['REB_home']+data['REB_away'])>130)

3

In [24]:
data['def'] = abs(data['PTS_home']-data['PTS_away'])

In [25]:
data

,SEASON,DATE,TEAM_home,TEAM_away,PTS_home,PTS_away,REB_home,REB_away,AST_home,AST_away,FG3_PCT_home,FG3_PCT_away,def
0,2019,2020-10-11,Miami Heat,Los Angeles Lakers,93,106,41,46,25,23,35.7,31.4,13
1,2019,2020-10-09,Los Angeles Lakers,Miami Heat,108,111,41,35,21,26,36.8,42.4,3
2,2019,2020-10-06,Miami Heat,Los Angeles Lakers,96,102,39,42,18,25,34.4,35.9,6
3,2019,2020-10-04,Miami Heat,Los Angeles Lakers,115,104,37,43,25,23,35.3,33.3,11
4,2019,2020-10-02,Los Angeles Lakers,Miami Heat,124,114,44,37,32,29,34.0,40.7,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23367,2014,2014-10-06,Atlanta Hawks,New Orleans Pelicans,93,87,50,43,24,17,42.1,37.5,6
23368,2014,2014-10-06,Chicago Bulls,Washington Wizards,81,85,40,47,18,17,38.1,26.7,4
23369,2014,2014-10-06,Los Angeles Lakers,Denver Nuggets,98,95,45,43,29,19,50.0,50.0,3
23370,2014,2014-10-05,Toronto Raptors,Sacramento Kings,99,94,30,45,21,18,33.3,38.5,5
23371,2014,2014-10-04,Miami Heat,New Orleans Pelicans,86,98,42,42,18,19,33.3,43.8,12

In [28]:
print(data[data['def'] == data['def'].max()])

       SEASON        DATE          TEAM_home          TEAM_away  PTS_home  \
17986    2017  2018-03-22  Charlotte Hornets  Memphis Grizzlies       140

       PTS_away  REB_home  REB_away  AST_home  AST_away  FG3_PCT_home  \
17986        79        53        38        25        13          47.5

       FG3_PCT_away  def
17986          22.2   61

In [42]:
data['win'] = 'NULL'
for i in range(len(data)):
    if data.PTS_home[i] > data.PTS_away[i]:
        st = data.TEAM_home[i]
    else: st = data.TEAM_away[i]
    data.win[i] = st

/tmp/ipykernel_12410/2082353064.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.win[i] = st

In [43]:
data

,SEASON,DATE,TEAM_home,TEAM_away,PTS_home,PTS_away,REB_home,REB_away,AST_home,AST_away,FG3_PCT_home,FG3_PCT_away,def,win
0,2019,2020-10-11,Miami Heat,Los Angeles Lakers,93,106,41,46,25,23,35.7,31.4,13,Los Angeles Lakers
1,2019,2020-10-09,Los Angeles Lakers,Miami Heat,108,111,41,35,21,26,36.8,42.4,3,Miami Heat
2,2019,2020-10-06,Miami Heat,Los Angeles Lakers,96,102,39,42,18,25,34.4,35.9,6,Los Angeles Lakers
3,2019,2020-10-04,Miami Heat,Los Angeles Lakers,115,104,37,43,25,23,35.3,33.3,11,Miami Heat
4,2019,2020-10-02,Los Angeles Lakers,Miami Heat,124,114,44,37,32,29,34.0,40.7,10,Los Angeles Lakers
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23367,2014,2014-10-06,Atlanta Hawks,New Orleans Pelicans,93,87,50,43,24,17,42.1,37.5,6,Atlanta Hawks
23368,2014,2014-10-06,Chicago Bulls,Washington Wizards,81,85,40,47,18,17,38.1,26.7,4,Washington Wizards
23369,2014,2014-10-06,Los Angeles Lakers,Denver Nuggets,98,95,45,43,29,19,50.0,50.0,3,Los Angeles Lakers
23370,2014,2014-10-05,Toronto Raptors,Sacramento Kings,99,94,30,45,21,18,33.3,38.5,5,Toronto Raptors
23371,2014,2014-10-04,Miami Heat,New Orleans Pelicans,86,98,42,42,18,19,33.3,43.8,12,New Orleans Pelicans

In [45]:
df = data.groupby('win')

In [48]:
(df['win'].size()).sort_values()[::-1]

win
San Antonio Spurs         1101
Miami Heat                 943
Houston Rockets            942
Boston Celtics             926
Dallas Mavericks           907
Golden State Warriors      886
Denver Nuggets             868
Oklahoma City Thunder      862
Los Angeles Lakers         851
Indiana Pacers             841
Cleveland Cavaliers        831
Utah Jazz                  817
Toronto Raptors            812
Los Angeles Clippers       797
Detroit Pistons            792
Chicago Bulls              784
Portland Trail Blazers     776
Phoenix Suns               755
Memphis Grizzlies          754
Orlando Magic              717
Atlanta Hawks              712
Milwaukee Bucks            707
New Orleans Pelicans       693
Washington Wizards         666
Philadelphia 76ers         656
Brooklyn Nets              653
Sacramento Kings           609
Minnesota Timberwolves     584
New York Knicks            577
Charlotte Hornets          553
Name: win, dtype: int64